### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by 553112** [Nestorboy/NUSaveState#1]
![image](https://user-images.githubusercontent.com/43203331/140266895-49c4576b-23ae-412e-9688-dc288812b3ec.png)

Hello, it's not a prefabs issue, but I'm curious how you changed the use Text in this picture.

**Comment by Nestorboy** [comment]
Using Udon, it's possible to set the interaction text of a pickup `string VRC_Pickup.InteractionText`, it is also worthy to note that the Udon Behaviour interaction text still remains unchangable through Udon.
As for the color and rescaling of the text, since I noticed that [Rich Text](https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/StyledText.html) is enabled, I format a string every frame to make it seem as if a rainbow is scrolling past and the letters are bouncing.

**Comment by 553112** [comment]
Thank you. That was a good reference.
