### ISSUE TITLE
Creator Companion

### ISSUE THREAD

**Issue by ghost** [Nestorboy/NUSaveState#4]
How can this be done within VRC Creator Companion.

**Comment by Nestorboy** [comment]
I've tested the prefab with U# 1.0 and the new VRC Creator Companion, and it's working as intended apart from a small bug.
There's an issue where if the 'Parameter Writers' array length is 0, it will prevent most of the inspector from showing up. To remedy this for now, you can use the debug inspector and set the length of the 'Parameter Writers' array to 1.
You still need to import the `VRCSDK3A.dll` in order to generate certain assets that depend on behaviours from the avatar SDK.

**Comment by ghost** [comment]
How can I get the avatar sdk in it.

**Comment by Nestorboy** [comment]
You only want one file from the avatar SDK. If you have a Unity Package for the SDK, then you should be able to follow the instructions under the 'Requirements' from the [README](https://github.com/Nestorboy/NUSaveState#requirements).
If you don't have an avatar SDK Unity Package, you could probably just create a new project for avatars and pull the aforementioned dll from there.
